version: '3'

services:
  asr-app:
    image: fastwhisper:latest
    shm_size: '4gb'
    environment:
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - './app/code/:/opt/project'
    ports:
      - "7860:7860"